spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/chemstore_test_db"
    username: chemstore_test_db_user
    password: chemstore_test_db_user
#logging.level:
#  root: DEBUG
#  org.hibernate:
#    SQL: DEBUG
#    type.descriptor.sql.BasicBinder: TRACE