spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://ec2-176-34-211-0.eu-west-1.compute.amazonaws.com:5432/des1rkcuqotmur"
    username: gxelnlhqbvoxpi
    password: 08eb51bd7bc524abf28f0f66ef15574810f4fa77b2481576b84ab2916eca7ff4
server
  port: ${PORT:8080}
#logging.level:
#  root: DEBUG
#  org.hibernate:
#    SQL: DEBUG
#    type.descriptor.sql.BasicBinder: TRACE