spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://ec2-54-155-194-191.eu-west-1.compute.amazonaws.com:5432/dfr9v1osb8qusq"
    username: ugjvgkbskrntym
    password: d8fc19729e98c959ef99e8e5b01e92ad1496017ca05f08b8b986465cad37690e
server
  port: ${PORT:8080}
#logging.level:
#  root: DEBUG
#  org.hibernate:
#    SQL: DEBUG
#    type.descriptor.sql.BasicBinder: TRACE