spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${db_url:jdbc:postgresql://localhost:5432/chemstore_db}
    username: ${db_username:chemstore_db_user}
    password: ${db_password:chemstore_db_user}